version: '3.8'

services:
  mole-server:
    build: .
    ports:
      - "${MOLE_PORT:-3000}:3000"
    volumes:
      - letsencrypt_data:/var/lib/letsencrypt
      - letsencrypt_logs:/var/log/letsencrypt  
      - letsencrypt_certs:/etc/letsencrypt
      - mole_logs:/var/log
    restart: unless-stopped
    networks:
      - mole-network
    env_file:
      - path: .env

volumes:
  letsencrypt_data:
  letsencrypt_logs:
  letsencrypt_certs:
  mole_logs:

networks:
  mole-network:
    driver: bridge